INSERT INTO film(ID,ANNEE,NOM,PRIX,SYNOPSIS,TYPE,URL_IMAGE) VALUES(1,2019,'Film1',6666, 'SYN','COMEDIE','TEST');
INSERT INTO film(ID,ANNEE,NOM,PRIX,SYNOPSIS,TYPE,URL_IMAGE) VALUES(2,2019,'Film2',6666, 'SYN','COMEDIE','TEST');
INSERT INTO film(ID,ANNEE,NOM,PRIX,SYNOPSIS,TYPE,URL_IMAGE) VALUES(3,2019,'Film3',6666, 'SYN','COMEDIE','TEST');
INSERT INTO film(ID,ANNEE,NOM,PRIX,SYNOPSIS,TYPE,URL_IMAGE) VALUES(4,2019,'Film4',6666, 'SYN','COMEDIE','TEST');
INSERT INTO film(ID,ANNEE,NOM,PRIX,SYNOPSIS,TYPE,URL_IMAGE) VALUES(5,2019,'Film5',6666, 'SYN','COMEDIE','TEST');